### PR TITLE
PLT-9072: Support GHC 9.6.2

### PR DESCRIPTION
**Pull request by sjoerdvisscher**
Pre-submit checklist:
- Branch
    - [ ] Tests are provided (if possible)
    - [ ] Commit sequence broadly makes sense and have useful messages
    - [ ] Important changes are reflected in changelog.d of the affected packages
    - [ ] Relevant tickets are mentioned in commit messages
- PR
    - [ ] (For external contributions) Corresponding issue exists and is linked in the description
    - [ ] Targeting main unless this is a cherry-pick backport
    - [ ] Self-reviewed the diff
    - [ ] Useful pull request description
    - [ ] If relevant, reference the ADR in the PR and reference the PR in the ADR
    - [ ] Reviewer requested

### CODE REVIEW

**Comment by sjoerdvisscher** [comment]
Mac tests are failing because the disk is full, so ignore that!

**Comment by berewt** [comment]
Can you warn the devx-team about the mac issue? (although it's likely that they know about it)

**Comment by sjoerdvisscher** [comment]
@berewt @kayvank I'm done with pushing changes, since CHaP is now green with these updates: https://github.com/IntersectMBO/cardano-haskell-packages/pull/635

**Comment by sjoerdvisscher** [comment]
@berewt No, it's still failing because the disk is full. The `The use of ‘~’ without TypeOperators` warnings are in a dependency.

**Pull request merged**
